development:
  adapter: postgresql
  encoding: utf8
  database: omnibrel_development
  host: localhost
  pool: 5
  username: ryan
  password: NightFire

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: omnibrel_test
  host: localhost
  pool: 5
  username: ryan
  password: NightFire

production:
  adapter: postgresql
  encoding: utf8
  database: omnibrel_production
  host: localhost
  pool: 5
  username: ryan
  password: NightFire

cucumber:
  <<: *TEST